'use strict';
const $=id=>document.getElementById(id);
let conversation=null,requestId=null,source=null,busy=false;
async function api(path,value){const options={credentials:'same-origin'};if(value!==undefined){options.method='POST';options.headers={'Content-Type':'application/json','X-Chat-Request':'1'};options.body=JSON.stringify(value);}const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw Error(data.error||'接続エラー');return data;}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
// Restricted Markdown, built from DOM nodes. Raw HTML and remote resources never execute.
function inline(text,node){for(const part of text.split(/(`[^`]+`|\*\*[^*]+\*\*)/g)){const el=part.startsWith('`')?document.createElement('code'):part.startsWith('**')?document.createElement('strong'):null;if(el){el.textContent=part.slice(part.startsWith('**')?2:1,part.startsWith('**')?-2:-1);node.append(el);}else node.append(document.createTextNode(part));}}
function markdown(text,node){node.replaceChildren();const blocks=text.split(/```/);blocks.forEach((part,i)=>{if(i%2){const pre=document.createElement('pre'),code=document.createElement('code');const line=part.indexOf('\n');code.textContent=line>=0?part.slice(line+1):part;pre.append(code);node.append(pre);}else{for(const line of part.split('\n')){const h=line.match(/^(#{1,3})\s+(.*)$/);const el=document.createElement(h?'h'+(h[1].length+1):'p');inline(h?h[2]:line||'\u00a0',el);node.append(el);}}});}
function message(role,text,metadata){$('messages').querySelector('.welcome')?.remove();const box=document.createElement('article');box.className='message '+role;const label=document.createElement('div');label.className='role';label.textContent=role==='user'?'あなた':'LocalBrain';const body=document.createElement('div');body.className='content';markdown(text,body);box.append(label,body);$('messages').append(box);if(metadata?.sources?.length){const s=document.createElement('div');s.className='sources';s.textContent=metadata.sources.map(x=>`[${x.source}] ${x.path} (${x.revision.slice(0,8)})`).join('\n');box.append(s);}return body;}
function setBusy(value){busy=value;for(const id of ['send','new','brain'])$(id).disabled=value;$('stop').disabled=!value;$('delete').disabled=value||!conversation;document.querySelectorAll('#chats button').forEach(x=>x.disabled=value);}
async function list(){const data=await api('/api/conversations');if(!busy&&conversation&&!data.conversations.some(c=>c.id===conversation)){conversation=null;$('title').textContent='新しいChat';$('messages').replaceChildren();$('details').textContent='';$('delete').disabled=true;status('このChatは削除されました');}$('chats').replaceChildren();for(const c of data.conversations){const b=document.createElement('button');b.textContent=c.title;b.className=c.id===conversation?'selected':'';b.disabled=busy;b.onclick=()=>openChat(c.id,c.title);$('chats').append(b);}}
async function openChat(id,title){if(busy)return;conversation=id;$('delete').disabled=false;$('title').textContent=title;$('messages').replaceChildren();const data=await api('/api/conversations/'+id);for(const m of data.messages)message(m.role,m.content,m.metadata);await list();$('messages').scrollTop=$('messages').scrollHeight;}
async function newChat(){const c=await api('/api/conversations',{});await openChat(c.id,'新しいChat');$('details').textContent='';$('prompt').focus();}
$('new').onclick=()=>newChat().catch(e=>status(e.message,true));
$('delete').onclick=async()=>{if(busy||!conversation)return;if(!window.confirm('このChatと会話履歴をLAN内の全ブラウザの共通履歴から削除します。元に戻せません。\nSecondBrainの知識は削除されません。\n削除しますか？'))return;setBusy(true);try{await api('/api/conversations/delete',{conversation_id:conversation,confirm:true});conversation=null;$('title').textContent='新しいChat';$('messages').replaceChildren();$('details').textContent='';status('Chatを削除しました');}catch(e){status(e.message,true);}finally{setBusy(false);await list();}};
$('brain').onchange=()=>{$('brain').parentElement.lastChild.textContent=' SecondBrain '+($('brain').checked?'ON':'OFF');};
$('prompt').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('form').requestSubmit();}};
$('stop').onclick=async()=>{if(requestId){$('stop').disabled=true;status('停止中…');try{await api('/api/stop/'+requestId,{});}catch(e){status(e.message,true);}}};
$('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const prompt=$('prompt').value.trim();if(!prompt)return;let body,text='',metadata={},warnings=[];try{if(!conversation)await newChat();setBusy(true);message('user',prompt);body=message('assistant','');$('prompt').value='';$('details').textContent='';status('Waiting');const job=await api('/api/chat',{conversation_id:conversation,message:prompt,secondbrain:$('brain').checked});requestId=job.request_id;source=new EventSource('/api/events/'+requestId);source.onmessage=async event=>{const data=JSON.parse(event.data);if(data.type==='state')status(data.state);if(data.type==='warning'){warnings.push(data.message);$('details').textContent=warnings.join(' · ');}if(data.type==='metadata'){metadata=data;$('details').textContent=[...warnings,`検索 ${data.retrieval_count}件 · context ${data.context_tokens.toLocaleString()} / 32,768 · 出力予約 ${data.output_reservation}`].join(' · ');}if(data.type==='delta'){text+=data.text;markdown(text,body);$('messages').scrollTop=$('messages').scrollHeight;}if(data.type==='error')status(data.message,true);if(data.type==='done'){source.close();source=null;requestId=null;setBusy(false);if(data.status==='completed'){status('完了');await openChat(conversation,prompt.slice(0,60));}else{status(data.status==='Cancelled'?'停止しました（途中の応答は履歴に保存されません）':data.status,true);}await list();}};source.onerror=()=>{source.close();source=null;const id=requestId;requestId=null;setBusy(false);status('接続が切れました。会話を開き直して履歴を確認してください。',true);if(id)api('/api/stop/'+id,{}).catch(()=>{});};}catch(error){setBusy(false);status(error.message,true);}};
(async()=>{try{await list();const h=await api('/api/health');status(h.gateway==='ok'?`接続済み · Qwen ${h.qwen}`:'Gateway unavailable');}catch(e){status(e.message,true);}})();
function refreshSharedList(){if(!busy&&!document.hidden)list().catch(e=>status(e.message,true));}
window.addEventListener('focus',refreshSharedList);
document.addEventListener('visibilitychange',refreshSharedList);
setInterval(refreshSharedList,5000);
